Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "./test2_nd.py", line 58, in <module>
    run()
  File "./test2_nd.py", line 19, in run
    (x_train, t_train), (x_test, t_test) = load_nd()
  File "../dataset/nd.py", line 127, in load_nd
    dataset = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 6: ordinal not in range(128)
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[29751,1],32]
  Exit code:    1
--------------------------------------------------------------------------
